#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Sat Apr 18 20:48:31 BRT 2026
enableDebugOptions=false
disableUpdateMessage=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
